
import { ColorStage, Pigment, MeaningComparison, IsccEntry } from './types';

export const BERLIN_KAY_STAGES: ColorStage[] = [
  {
    id: 1,
    title: "Stage I: Light & Dark",
    description: "Two terms emerge: one for 'warm/light' colors and one for 'cool/dark' colors.",
    colors: ['#FFFFFF', '#000000', '#FF0000'],
    colorNames: ['White/Warm', 'Black/Cool']
  },
  {
    id: 2,
    title: "Stage II: Red Emerges",
    description: "Red emerges as a distinct category separate from the light/warm group.",
    colors: ['#FFFFFF', '#000000', '#D93025'],
    colorNames: ['White', 'Black', 'Red']
  },
  {
    id: 3,
    title: "Stage III/IV: Green or Yellow",
    description: "Either Green or Yellow appears next. The order varies by language.",
    colors: ['#FFFFFF', '#000000', '#D93025', '#1E8E3E', '#F9AB00'],
    colorNames: ['White', 'Black', 'Red', 'Green/Yellow']
  },
  {
    id: 4,
    title: "Stage V: Blue Arrives",
    description: "Blue is added. Many languages have a 'grue' term covering green and blue before this.",
    colors: ['#FFFFFF', '#000000', '#D93025', '#1E8E3E', '#F9AB00', '#1A73E8'],
    colorNames: ['White', 'Black', 'Red', 'Green', 'Yellow', 'Blue']
  },
  {
    id: 5,
    title: "Stage VI: Brown",
    description: "Brown is added as a distinct term.",
    colors: ['#FFFFFF', '#000000', '#D93025', '#1E8E3E', '#F9AB00', '#1A73E8', '#795548'],
    colorNames: ['White', 'Black', 'Red', 'Green', 'Yellow', 'Blue', 'Brown']
  },
  {
    id: 6,
    title: "Stage VII: The Full Spectrum",
    description: "Purple, Pink, Orange, and Gray appear in no fixed order to complete the basic set.",
    colors: ['#FFFFFF', '#000000', '#D93025', '#1E8E3E', '#F9AB00', '#1A73E8', '#795548', '#9334E6', '#E91E63', '#F4511E', '#9AA0A6'],
    colorNames: ['White', 'Black', 'Red', 'Green', 'Yellow', 'Blue', 'Brown', 'Purple', 'Pink', 'Orange', 'Gray']
  }
];

export const PIGMENTS: Pigment[] = [
  {
    id: 'quercitron',
    name: 'Quercitron',
    description: 'A shade of yellow dye produced from the bark of an oak tree.',
    origin: 'Latin quercus (oak) + citron.',
    hex: '#E3C565', // Approximated from image
    category: 'natural'
  },
  {
    id: 'annatto',
    name: 'Annatto',
    description: 'A yellowish-red color from the pulp of the lipstick tree seed, used to color butter and cheese.',
    origin: 'Borrowed from the Carib language.',
    hex: '#D64024',
    category: 'natural'
  },
  {
    id: 'gamboge',
    name: 'Gamboge',
    description: 'A yellow-orange gum resin from a tree native to Cambodia.',
    origin: 'From the Latin name for the country, cambogium.',
    hex: '#EF9B0F',
    category: 'natural'
  },
  {
    id: 'sepia',
    name: 'Sepia',
    description: 'A brown, grayish, or olive brown pigment secreted by cuttlefish.',
    origin: 'Latin sēpia, meaning "cuttlefish".',
    hex: '#704214',
    category: 'natural'
  },
  {
    id: 'ultramarine',
    name: 'Ultramarine',
    description: 'A deep-blue color, historically made from lapis lazuli. Imported to Europe from "beyond the sea".',
    origin: 'Medieval Latin ultramarinus.',
    hex: '#120A8F',
    category: 'power'
  },
  {
    id: 'tyrian',
    name: 'Tyrian Purple',
    description: 'A vivid, purplish red highly prized by the Byzantine empire. Extracted from sea snails.',
    origin: 'Named after Tyre, Lebanon.',
    hex: '#66023C',
    category: 'power'
  },
  {
    id: 'smaragdine',
    name: 'Smaragdine',
    description: 'An emerald-green color. First recorded in English as early as 1350.',
    origin: 'Greek smarágdinos (emerald).',
    hex: '#009b7d',
    category: 'history'
  },
  {
    id: 'dragonsblood',
    name: "Dragon's Blood",
    description: 'A dull, grayish red resin that exudes from the fruit of certain palm trees.',
    origin: 'Named for the deep-red resin.',
    hex: '#AA1122',
    category: 'history'
  }
];

export const CULTURAL_MEANINGS: MeaningComparison[] = [
  {
    color: 'Red',
    hex: '#C8102E',
    western: {
      positive: ['Love', 'Passion', 'Life'],
      negative: ['War (Mars)', 'Danger', 'Sin']
    },
    eastern: {
      positive: ['Good Fortune', 'Happiness', 'Celebration'],
      negative: ['(Rarely negative in this context)']
    }
  },
  {
    color: 'White',
    hex: '#F0F0F0',
    western: {
      positive: ['Purity', 'Innocence', 'The Divine'],
      negative: ['Paleness', 'Cowardice']
    },
    eastern: {
      positive: ['Symbol of Autumn', 'Metal Element'],
      negative: ['Mourning', 'Funerals', 'Treachery (Opera)']
    }
  }
];

export const ISCC_SAMPLES: IsccEntry[] = [
  // Pinks
  { id: 1, name: "Vivid Pink", hex: "#FFB5BA", category: "Pink" },
  { id: 2, name: "Strong Pink", hex: "#EA9399", category: "Pink" },
  { id: 3, name: "Deep Pink", hex: "#E4717A", category: "Pink" },
  { id: 4, name: "Light Pink", hex: "#F9CCCA", category: "Pink" },
  { id: 5, name: "Moderate Pink", hex: "#DEA5A4", category: "Pink" },
  { id: 6, name: "Dark Pink", hex: "#C08081", category: "Pink" },
  { id: 7, name: "Pale Pink", hex: "#EAD8D7", category: "Pink" },
  { id: 8, name: "Grayish Pink", hex: "#C4A4A4", category: "Pink" },
  { id: 9, name: "Pinkish White", hex: "#EAE3E1", category: "White" },
  { id: 10, name: "Pinkish Gray", hex: "#C1B6B3", category: "Gray" },
  // Reds
  { id: 11, name: "Vivid Red", hex: "#BE0032", category: "Red" },
  { id: 12, name: "Strong Red", hex: "#BC3F4A", category: "Red" },
  { id: 13, name: "Deep Red", hex: "#841B2D", category: "Red" },
  { id: 14, name: "Very Deep Red", hex: "#5C0923", category: "Red" },
  { id: 15, name: "Moderate Red", hex: "#AB4E52", category: "Red" },
  { id: 16, name: "Dark Red", hex: "#722F37", category: "Red" },
  { id: 17, name: "Very Dark Red", hex: "#3F1728", category: "Red" },
  { id: 18, name: "Light Grayish Red", hex: "#AC8888", category: "Red" },
  { id: 19, name: "Grayish Red", hex: "#905D5D", category: "Red" },
  { id: 20, name: "Dark Grayish Red", hex: "#5C3C3C", category: "Red" },
  { id: 21, name: "Blackish Red", hex: "#2E1D21", category: "Red" },
  { id: 22, name: "Reddish Gray", hex: "#8F8181", category: "Gray" },
  { id: 23, name: "Dark Reddish Gray", hex: "#5F5454", category: "Gray" },
  { id: 24, name: "Reddish Black", hex: "#282424", category: "Black" },
  // Reddish Oranges / Oranges
  { id: 25, name: "Vivid Reddish Orange", hex: "#DD4124", category: "Orange" },
  { id: 26, name: "Strong Reddish Orange", hex: "#D9603B", category: "Orange" },
  { id: 27, name: "Deep Reddish Orange", hex: "#AA3C27", category: "Orange" },
  { id: 28, name: "Moderate Reddish Orange", hex: "#CB6843", category: "Orange" },
  { id: 29, name: "Dark Reddish Orange", hex: "#8F402A", category: "Orange" },
  { id: 30, name: "Grayish Reddish Orange", hex: "#B37E6F", category: "Orange" },
  { id: 31, name: "Strong Reddish Brown", hex: "#882D17", category: "Brown" },
  { id: 32, name: "Deep Reddish Brown", hex: "#571E15", category: "Brown" },
  { id: 33, name: "Light Reddish Brown", hex: "#A87C6D", category: "Brown" },
  { id: 34, name: "Moderate Reddish Brown", hex: "#79443B", category: "Brown" },
  { id: 35, name: "Dark Reddish Brown", hex: "#46221E", category: "Brown" },
  { id: 36, name: "Vivid Orange", hex: "#F38400", category: "Orange" },
  { id: 37, name: "Brilliant Orange", hex: "#FD943F", category: "Orange" },
  { id: 38, name: "Strong Orange", hex: "#ED872D", category: "Orange" },
  { id: 39, name: "Deep Orange", hex: "#BE6528", category: "Orange" },
  { id: 40, name: "Light Orange", hex: "#FAB57F", category: "Orange" },
  { id: 41, name: "Moderate Orange", hex: "#D99058", category: "Orange" },
  { id: 42, name: "Dark Orange", hex: "#AE6938", category: "Orange" },
  { id: 43, name: "Pale Orange", hex: "#F3C597", category: "Orange" },
  { id: 44, name: "Grayish Orange", hex: "#B89173", category: "Orange" },
  { id: 45, name: "Dark Grayish Orange", hex: "#8C694F", category: "Orange" },
  { id: 46, name: "Strong Brown", hex: "#80461B", category: "Brown" },
  { id: 47, name: "Deep Brown", hex: "#593110", category: "Brown" },
  { id: 48, name: "Light Brown", hex: "#A67B5B", category: "Brown" },
  { id: 49, name: "Moderate Brown", hex: "#6F4E37", category: "Brown" },
  { id: 50, name: "Dark Brown", hex: "#422518", category: "Brown" },
  { id: 51, name: "Light Grayish Brown", hex: "#958679", category: "Brown" },
  { id: 52, name: "Grayish Brown", hex: "#635147", category: "Brown" },
  { id: 53, name: "Dark Grayish Brown", hex: "#3E322C", category: "Brown" },
  { id: 54, name: "Brownish Orange", hex: "#AE6E43", category: "Orange" },
  { id: 55, name: "Strong Brownish Orange", hex: "#A05A2C", category: "Orange" },
  { id: 56, name: "Deep Brownish Orange", hex: "#783F16", category: "Orange" },
  // Yellows / Olives
  { id: 57, name: "Light Brownish Orange", hex: "#C79B7B", category: "Orange" },
  { id: 58, name: "Moderate Brownish Orange", hex: "#8C5836", category: "Orange" },
  { id: 59, name: "Dark Brownish Orange", hex: "#61381D", category: "Orange" },
  { id: 60, name: "Light Brownish Gray", hex: "#8E8279", category: "Gray" },
  { id: 61, name: "Brownish Gray", hex: "#5F544D", category: "Gray" },
  { id: 62, name: "Brownish Black", hex: "#292421", category: "Black" },
  { id: 63, name: "Vivid Orange Yellow", hex: "#F6A600", category: "Yellow" },
  { id: 64, name: "Brilliant Orange Yellow", hex: "#FFC14F", category: "Yellow" },
  { id: 65, name: "Strong Orange Yellow", hex: "#EAAA00", category: "Yellow" },
  { id: 66, name: "Deep Orange Yellow", hex: "#C99700", category: "Yellow" },
  { id: 67, name: "Light Orange Yellow", hex: "#F8CF7D", category: "Yellow" },
  { id: 68, name: "Moderate Orange Yellow", hex: "#DFA956", category: "Yellow" },
  { id: 69, name: "Dark Orange Yellow", hex: "#AA7D39", category: "Yellow" },
  { id: 70, name: "Pale Orange Yellow", hex: "#EFD69B", category: "Yellow" },
  { id: 71, name: "Moderate Olive Brown", hex: "#6E5236", category: "Brown" },
  { id: 72, name: "Dark Olive Brown", hex: "#412E1E", category: "Brown" },
  { id: 73, name: "Pale Yellow", hex: "#F3E5AB", category: "Yellow" },
  { id: 74, name: "Grayish Yellow", hex: "#C2B280", category: "Yellow" },
  { id: 75, name: "Dark Grayish Yellow", hex: "#928459", category: "Yellow" },
  { id: 76, name: "Light Yellowish Brown", hex: "#C0A678", category: "Brown" },
  { id: 77, name: "Moderate Yellowish Brown", hex: "#876D45", category: "Brown" },
  { id: 78, name: "Dark Yellowish Brown", hex: "#523F27", category: "Brown" },
  { id: 79, name: "Light Grayish Yellowish Brown", hex: "#988C78", category: "Brown" },
  { id: 80, name: "Grayish Yellowish Brown", hex: "#685C4B", category: "Brown" },
  { id: 81, name: "Dark Grayish Yellowish Brown", hex: "#42382D", category: "Brown" },
  { id: 82, name: "Vivid Yellow", hex: "#F3C300", category: "Yellow" },
  { id: 83, name: "Brilliant Yellow", hex: "#F2C649", category: "Yellow" },
  { id: 84, name: "Strong Yellow", hex: "#D4AF37", category: "Yellow" },
  { id: 85, name: "Deep Yellow", hex: "#A88905", category: "Yellow" },
  { id: 86, name: "Light Yellow", hex: "#F8DE7E", category: "Yellow" },
  { id: 87, name: "Moderate Yellow", hex: "#C9AE5D", category: "Yellow" },
  { id: 88, name: "Dark Yellow", hex: "#9B8436", category: "Yellow" },
  { id: 89, name: "Pale Yellow", hex: "#F1E4B3", category: "Yellow" },
  { id: 90, name: "Grayish Yellow", hex: "#BDAF82", category: "Yellow" },
  { id: 91, name: "Dark Grayish Yellow", hex: "#8F8155", category: "Yellow" },
  { id: 92, name: "Yellowish White", hex: "#F0EAD6", category: "White" },
  { id: 93, name: "Yellowish Gray", hex: "#BFB8A5", category: "Gray" },
  { id: 94, name: "Light Olive Brown", hex: "#927D4C", category: "Brown" },
  { id: 95, name: "Moderate Olive Brown", hex: "#665431", category: "Brown" },
  { id: 96, name: "Dark Olive Brown", hex: "#3A2F1A", category: "Brown" },
  // Greenish Yellows
  { id: 97, name: "Vivid Greenish Yellow", hex: "#DCD300", category: "Yellow" },
  { id: 98, name: "Brilliant Greenish Yellow", hex: "#E9E450", category: "Yellow" },
  { id: 99, name: "Strong Greenish Yellow", hex: "#BEB72E", category: "Yellow" },
  { id: 100, name: "Deep Greenish Yellow", hex: "#9B9400", category: "Yellow" },
  { id: 101, name: "Light Greenish Yellow", hex: "#EAE679", category: "Yellow" },
  { id: 102, name: "Moderate Greenish Yellow", hex: "#B9B459", category: "Yellow" },
  { id: 103, name: "Dark Greenish Yellow", hex: "#8C873E", category: "Yellow" },
  { id: 104, name: "Pale Greenish Yellow", hex: "#EBE8A4", category: "Yellow" },
  { id: 105, name: "Grayish Greenish Yellow", hex: "#B9B57D", category: "Yellow" },
  { id: 106, name: "Light Olive", hex: "#867E36", category: "Olive" },
  { id: 107, name: "Moderate Olive", hex: "#665D1E", category: "Olive" },
  { id: 108, name: "Dark Olive", hex: "#403D21", category: "Olive" },
  { id: 109, name: "Light Grayish Olive", hex: "#8A8768", category: "Olive" },
  { id: 110, name: "Grayish Olive", hex: "#5B5842", category: "Olive" },
  { id: 111, name: "Dark Grayish Olive", hex: "#363527", category: "Olive" },
  { id: 112, name: "Light Olive Gray", hex: "#8C8979", category: "Gray" },
  { id: 113, name: "Olive Gray", hex: "#5D5A4C", category: "Gray" },
  { id: 114, name: "Olive Black", hex: "#262521", category: "Black" },
  // Yellow Greens
  { id: 115, name: "Vivid Yellow Green", hex: "#8DB600", category: "Green" },
  { id: 116, name: "Brilliant Yellow Green", hex: "#BDDA57", category: "Green" },
  { id: 117, name: "Strong Yellow Green", hex: "#7E9F2E", category: "Green" },
  { id: 118, name: "Deep Yellow Green", hex: "#4A5D23", category: "Green" },
  { id: 119, name: "Light Yellow Green", hex: "#C9DC89", category: "Green" },
  { id: 120, name: "Moderate Yellow Green", hex: "#8A9A5B", category: "Green" },
  { id: 121, name: "Pale Yellow Green", hex: "#DADFB7", category: "Green" },
  { id: 122, name: "Grayish Yellow Green", hex: "#8F9779", category: "Green" },
  { id: 123, name: "Strong Olive Green", hex: "#556B2F", category: "Green" },
  { id: 124, name: "Deep Olive Green", hex: "#354A21", category: "Green" },
  { id: 125, name: "Moderate Olive Green", hex: "#4A5D23", category: "Green" },
  { id: 126, name: "Dark Olive Green", hex: "#313D1F", category: "Green" },
  // Greens
  { id: 127, name: "Grayish Olive Green", hex: "#515744", category: "Green" },
  { id: 128, name: "Dark Grayish Olive Green", hex: "#31352B", category: "Green" },
  { id: 129, name: "Vivid Yellowish Green", hex: "#27A64C", category: "Green" },
  { id: 130, name: "Brilliant Yellowish Green", hex: "#66C07D", category: "Green" },
  { id: 131, name: "Strong Yellowish Green", hex: "#44944A", category: "Green" },
  { id: 132, name: "Deep Yellowish Green", hex: "#00622D", category: "Green" },
  { id: 133, name: "Very Deep Yellowish Green", hex: "#003618", category: "Green" },
  { id: 134, name: "Light Yellowish Green", hex: "#93C592", category: "Green" },
  { id: 135, name: "Moderate Yellowish Green", hex: "#679267", category: "Green" },
  { id: 136, name: "Dark Yellowish Green", hex: "#385638", category: "Green" },
  { id: 137, name: "Very Dark Yellowish Green", hex: "#1C2C1C", category: "Green" },
  { id: 138, name: "Vivid Green", hex: "#008856", category: "Green" },
  { id: 139, name: "Brilliant Green", hex: "#3EB489", category: "Green" },
  { id: 140, name: "Strong Green", hex: "#007959", category: "Green" },
  { id: 141, name: "Deep Green", hex: "#005432", category: "Green" },
  { id: 142, name: "Very Deep Green", hex: "#00301C", category: "Green" },
  { id: 143, name: "Light Green", hex: "#8FD5A6", category: "Green" },
  { id: 144, name: "Moderate Green", hex: "#5E8C6A", category: "Green" },
  { id: 145, name: "Dark Green", hex: "#304E37", category: "Green" },
  { id: 146, name: "Very Dark Green", hex: "#182A1C", category: "Green" },
  { id: 147, name: "Pale Green", hex: "#B3DBC1", category: "Green" },
  { id: 148, name: "Grayish Green", hex: "#7A9581", category: "Green" },
  { id: 149, name: "Dark Grayish Green", hex: "#495A4E", category: "Green" },
  { id: 150, name: "Blackish Green", hex: "#222B25", category: "Green" },
  { id: 151, name: "Greenish White", hex: "#DFEDE8", category: "White" },
  { id: 152, name: "Light Greenish Gray", hex: "#B4C0B9", category: "Gray" },
  { id: 153, name: "Greenish Gray", hex: "#7E8B83", category: "Gray" },
  { id: 154, name: "Dark Greenish Gray", hex: "#4D5551", category: "Gray" },
  { id: 155, name: "Greenish Black", hex: "#222624", category: "Black" },
  // Blue Greens
  { id: 156, name: "Vivid Bluish Green", hex: "#008882", category: "Green" },
  { id: 157, name: "Brilliant Bluish Green", hex: "#00A693", category: "Green" },
  { id: 158, name: "Strong Bluish Green", hex: "#007A74", category: "Green" },
  { id: 159, name: "Deep Bluish Green", hex: "#004B49", category: "Green" },
  { id: 160, name: "Very Deep Bluish Green", hex: "#002B2A", category: "Green" },
  { id: 161, name: "Light Bluish Green", hex: "#66C2BD", category: "Green" },
  { id: 162, name: "Moderate Bluish Green", hex: "#317873", category: "Green" },
  { id: 163, name: "Dark Bluish Green", hex: "#00443F", category: "Green" },
  { id: 164, name: "Very Dark Bluish Green", hex: "#002421", category: "Green" },
  { id: 165, name: "Vivid Greenish Blue", hex: "#0085A1", category: "Blue" },
  { id: 166, name: "Brilliant Greenish Blue", hex: "#239EBA", category: "Blue" },
  { id: 167, name: "Strong Greenish Blue", hex: "#007791", category: "Blue" },
  { id: 168, name: "Deep Greenish Blue", hex: "#004D5F", category: "Blue" },
  { id: 169, name: "Very Deep Greenish Blue", hex: "#002D38", category: "Blue" },
  { id: 170, name: "Light Greenish Blue", hex: "#6CDAE7", category: "Blue" },
  { id: 171, name: "Moderate Greenish Blue", hex: "#367588", category: "Blue" },
  { id: 172, name: "Dark Greenish Blue", hex: "#004953", category: "Blue" },
  { id: 173, name: "Very Dark Greenish Blue", hex: "#002B30", category: "Blue" },
  { id: 174, name: "Vivid Blue", hex: "#00A1C2", category: "Blue" },
  { id: 175, name: "Brilliant Blue", hex: "#4997D0", category: "Blue" },
  // Blues
  { id: 176, name: "Strong Blue", hex: "#0067A5", category: "Blue" },
  { id: 177, name: "Deep Blue", hex: "#00416A", category: "Blue" },
  { id: 178, name: "Very Deep Blue", hex: "#00233D", category: "Blue" },
  { id: 179, name: "Light Blue", hex: "#A4D3EE", category: "Blue" },
  { id: 180, name: "Moderate Blue", hex: "#5B92E5", category: "Blue" },
  { id: 181, name: "Dark Blue", hex: "#00308F", category: "Blue" },
  { id: 182, name: "Very Dark Blue", hex: "#001A33", category: "Blue" },
  { id: 183, name: "Pale Blue", hex: "#D1EAF0", category: "Blue" },
  { id: 184, name: "Grayish Blue", hex: "#90A0C0", category: "Blue" },
  { id: 185, name: "Dark Grayish Blue", hex: "#506080", category: "Blue" },
  { id: 186, name: "Blackish Blue", hex: "#202830", category: "Blue" },
  { id: 187, name: "Bluish White", hex: "#E6F0F5", category: "White" },
  { id: 188, name: "Light Bluish Gray", hex: "#B8C0C8", category: "Gray" },
  { id: 189, name: "Bluish Gray", hex: "#78858B", category: "Gray" },
  { id: 190, name: "Dark Bluish Gray", hex: "#485056", category: "Gray" },
  { id: 191, name: "Bluish Black", hex: "#202428", category: "Black" },
  // Purplish Blues
  { id: 192, name: "Vivid Purplish Blue", hex: "#4400CC", category: "Blue" },
  { id: 193, name: "Brilliant Purplish Blue", hex: "#6A5ACD", category: "Blue" },
  { id: 194, name: "Strong Purplish Blue", hex: "#3F00FF", category: "Blue" },
  { id: 195, name: "Deep Purplish Blue", hex: "#2A0080", category: "Blue" },
  { id: 196, name: "Very Deep Purplish Blue", hex: "#150040", category: "Blue" },
  { id: 197, name: "Light Purplish Blue", hex: "#B0C4DE", category: "Blue" },
  { id: 198, name: "Moderate Purplish Blue", hex: "#4D4DFF", category: "Blue" },
  { id: 199, name: "Dark Purplish Blue", hex: "#1F1F7A", category: "Blue" },
  { id: 200, name: "Very Dark Purplish Blue", hex: "#0F0F3D", category: "Blue" },
  { id: 201, name: "Pale Purplish Blue", hex: "#DBE4EB", category: "Blue" },
  { id: 202, name: "Grayish Purplish Blue", hex: "#8F8FA8", category: "Blue" },
  // Violets / Purples
  { id: 203, name: "Vivid Violet", hex: "#9F00FF", category: "Purple" },
  { id: 204, name: "Brilliant Violet", hex: "#D085FF", category: "Purple" },
  { id: 205, name: "Strong Violet", hex: "#7F00FF", category: "Purple" },
  { id: 206, name: "Deep Violet", hex: "#5500AA", category: "Purple" },
  { id: 207, name: "Very Deep Violet", hex: "#2A0055", category: "Purple" },
  { id: 208, name: "Light Violet", hex: "#E0B0FF", category: "Purple" },
  { id: 209, name: "Moderate Violet", hex: "#8040BF", category: "Purple" },
  { id: 210, name: "Dark Violet", hex: "#4B0082", category: "Purple" },
  { id: 211, name: "Very Dark Violet", hex: "#250041", category: "Purple" },
  { id: 212, name: "Pale Violet", hex: "#F0DCFA", category: "Purple" },
  { id: 213, name: "Grayish Violet", hex: "#8A7996", category: "Purple" },
  { id: 214, name: "Vivid Purple", hex: "#9A4EAE", category: "Purple" },
  { id: 215, name: "Brilliant Purple", hex: "#D399E6", category: "Purple" },
  { id: 216, name: "Strong Purple", hex: "#875692", category: "Purple" },
  { id: 217, name: "Deep Purple", hex: "#602F6B", category: "Purple" },
  { id: 218, name: "Very Deep Purple", hex: "#401A4C", category: "Purple" },
  { id: 219, name: "Light Purple", hex: "#D8BFD8", category: "Purple" },
  { id: 220, name: "Moderate Purple", hex: "#A070B0", category: "Purple" },
  { id: 221, name: "Dark Purple", hex: "#704080", category: "Purple" },
  { id: 222, name: "Very Dark Purple", hex: "#402050", category: "Purple" },
  { id: 223, name: "Pale Purple", hex: "#F3E1EB", category: "Purple" },
  { id: 224, name: "Grayish Purple", hex: "#998899", category: "Purple" },
  { id: 225, name: "Dark Grayish Purple", hex: "#605060", category: "Purple" },
  { id: 226, name: "Blackish Purple", hex: "#302830", category: "Purple" },
  { id: 227, name: "Purplish White", hex: "#EBE6EB", category: "White" },
  { id: 228, name: "Light Purplish Gray", hex: "#BFB8BF", category: "Gray" },
  { id: 229, name: "Purplish Gray", hex: "#8F808F", category: "Gray" },
  { id: 230, name: "Dark Purplish Gray", hex: "#5F505F", category: "Gray" },
  { id: 231, name: "Purplish Black", hex: "#2F202F", category: "Black" },
  // Reddish Purples
  { id: 232, name: "Vivid Reddish Purple", hex: "#CE0058", category: "Purple" },
  { id: 233, name: "Strong Reddish Purple", hex: "#AA4070", category: "Purple" },
  { id: 234, name: "Deep Reddish Purple", hex: "#801040", category: "Purple" },
  { id: 235, name: "Very Deep Reddish Purple", hex: "#500828", category: "Purple" },
  { id: 236, name: "Light Reddish Purple", hex: "#EFBBCC", category: "Purple" },
  { id: 237, name: "Moderate Reddish Purple", hex: "#B07090", category: "Purple" },
  { id: 238, name: "Dark Reddish Purple", hex: "#703050", category: "Purple" },
  { id: 239, name: "Very Dark Reddish Purple", hex: "#401828", category: "Purple" },
  { id: 240, name: "Pale Reddish Purple", hex: "#F0D0E0", category: "Purple" },
  { id: 241, name: "Grayish Reddish Purple", hex: "#A08090", category: "Purple" },
  { id: 242, name: "Dark Grayish Reddish Purple", hex: "#604050", category: "Purple" },
  { id: 243, name: "Vivid Purplish Red", hex: "#E6005C", category: "Red" },
  { id: 244, name: "Strong Purplish Red", hex: "#B33965", category: "Red" },
  { id: 245, name: "Deep Purplish Red", hex: "#7D1040", category: "Red" },
  { id: 246, name: "Very Deep Purplish Red", hex: "#540028", category: "Red" },
  { id: 247, name: "Light Purplish Red", hex: "#EBB8C8", category: "Red" },
  { id: 248, name: "Moderate Purplish Red", hex: "#AA6680", category: "Red" },
  { id: 249, name: "Dark Purplish Red", hex: "#703048", category: "Red" },
  { id: 250, name: "Very Dark Purplish Red", hex: "#401020", category: "Red" },
  { id: 251, name: "Pale Purplish Red", hex: "#F0C0D0", category: "Red" },
  { id: 252, name: "Grayish Purplish Red", hex: "#A07080", category: "Red" },
  { id: 253, name: "Strong Purplish Pink", hex: "#E68FAC", category: "Pink" },
  { id: 254, name: "Deep Purplish Pink", hex: "#C76587", category: "Pink" },
  { id: 255, name: "Light Purplish Pink", hex: "#EFB8CF", category: "Pink" },
  { id: 256, name: "Moderate Purplish Pink", hex: "#D69AB5", category: "Pink" },
  { id: 257, name: "Dark Purplish Pink", hex: "#A86989", category: "Pink" },
  { id: 258, name: "Pale Purplish Pink", hex: "#F0D8E4", category: "Pink" },
  { id: 259, name: "Grayish Purplish Pink", hex: "#C0A4B4", category: "Pink" },
  // Grays / Black / White
  { id: 260, name: "White", hex: "#F2F3F4", category: "White" },
  { id: 261, name: "Light Gray", hex: "#D3D3D3", category: "Gray" },
  { id: 262, name: "Medium Gray", hex: "#A9A9A9", category: "Gray" },
  { id: 263, name: "Dark Gray", hex: "#696969", category: "Gray" },
  { id: 264, name: "Light Gray", hex: "#B9B8B5", category: "Gray" }, 
  { id: 265, name: "Medium Gray", hex: "#848482", category: "Gray" },
  { id: 266, name: "Dark Gray", hex: "#555555", category: "Gray" },
  { id: 267, name: "Black", hex: "#000000", category: "Black" }
];
